language: c
dist: trusty
sudo: required

stages:
  - lint
  - test
  - sanity
  - installcheck
  - coverage

jobs:
  include:
    - stage: lint
      compiler: clang
      before_install:
        - pip install --user cpplint
        - sudo apt-get install -y clang-format || true
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make lint
        - make checkformat
    - stage: test
      compiler: gcc
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make distcheck
    - stage: test
      compiler: clang
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make distcheck
    - stage: test
      compiler: gcc
      dist: precise
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make distcheck
    - stage: test
      compiler: clang
      dist: precise
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make distcheck
    - stage: sanity
      compiler: gcc
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make sanity
    - stage: installcheck
      compiler: gcc
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make
        - sudo make install
        - make post-installcheck
    - stage: coverage
      compiler: gcc
      before_install:
        - pip install --user cpp-coveralls
        - sudo apt-get install -y lcov
        - gem install coveralls-lcov
      script:
        - ./autogen.sh --no-changelog
        - ./configure
        - make coverage
      after_success:
        - coveralls-lcov --repo-token ${COVERALLS_REPO_TOKEN} coverage.info
