
version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2017

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
    BUILDTOOL: make

install:
  - bash -c "pacman -S base-devel"
  - bash -c "mkdir -p /repos"
  - bash -c "cd /repos && git clone https://github.com/Alexpux/MINGW-packages.git"
  - bash -c "cd /repos/MINGW-packages/mingw-w64-libuv && updpkgsums"
  - bash -c "cd /repos/MINGW-packages/mingw-w64-libuv && makepkg-mingw -fsiL"
  - bash -c "cd /repos/MINGW-packages/mingw-w64-libuv && pacman -U migw-w64-libuv'''.pkg.tar.xz"
  
build_script:
  - bash -c "./autogen.sh --no-changelog"
  - bash -c "./configure"
  - bash -c "make"
  
test_script:
  - bash -c "make check"
