
version: '{build}'

branches:
  only:
    - master
    
os: Visual Studio 2017

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64
    BUILDTOOL: make

install:
  - mkdir --help
  - /usr/bin/mkdir --help
  - which mkdir
  - mkdir -p /repos
  - cd /repos && git clone https://github.com/Alexpux/MINGW-packages.git
  - cd /repos/MINGW-packages/mingw-w64-libuv && updpkgsums
  - cd /repos/MINGW-packages/mingw-w64-libuv && makepkg-mingw -fsiL
  - cd /repos/MINGW-packages/mingw-w64-libuv && pacman -U migw-w64-libuv'''.pkg.tar.xz
  
build_script:
  - ./autogen.sh --no-changelog
  - ./configure
  - make
  
test_script:
  - make check
